# merge to a destination branch
platform: linux
image_resource:
  type: docker-image
  source:
    repository: mgbi/oauth-git
inputs:
  - name: source-branch
params:
  DESTINATION_BRANCH:
  OAUTH_CLIENT_KEY:
  OAUTH_CLIENT_SECRET:
run:
  dir: source-branch
  path: sh
  args:
    - -exc
    - |
      git config user.email "admin@mgbi.pl"
      git config user.name "Concourse CI"
      OAUTH_ACCESS_TOKEN=$(git-oauth-token) git-merge-into-remote-branch $DESTINATION_BRANCH
