# init MongoDB replica set and add users
platform: linux
image_resource:
  type: docker-image
  source:
    repository: mgbi/rancher-cli
params:
  RANCHER_URL:
  RANCHER_ACCESS_KEY:
  RANCHER_SECRET_KEY:
  RANCHER_CONTAINER_NAME:
run:
  path: sh
  args:
    - -exc
    - |
      rancher exec $RANCHER_CONTAINER_NAME init-replica-set
      rancher exec $RANCHER_CONTAINER_NAME init-admin-users
      rancher exec $RANCHER_CONTAINER_NAME init-users
